### PR TITLE
fix: ci

### PR DESCRIPTION
**Pull request by JaeAeich**
## Summary by Sourcery

This pull request introduces significant enhancements to the project structure, including a revamped README.md, a Makefile for common tasks, Sphinx configuration for documentation, multiple GitHub Actions workflows for CI/CD, a Code of Conduct, a pull request template, pre-commit hooks, and placeholder test files. Additionally, it includes configuration files for Read the Docs and YAML linting.

- **Enhancements**:
    - Revamped README.md with badges, table of contents, and detailed sections for usage, installation, development, contributing, code of conduct, versioning, license, and contact information.
    - Added a Makefile to streamline common development tasks such as creating virtual environments, installing dependencies, running tests, and generating documentation.
    - Introduced a Sphinx configuration file (conf.py) for generating project documentation.
    - Added a custom GitHub Action for setting up Python and Poetry environments.
    - Created multiple GitHub workflows for code quality checks, testing, PR validation, documentation checks, and vulnerability scans.
    - Added a Code of Conduct document to outline community standards and enforcement policies.
    - Included a PULL_REQUEST_TEMPLATE.md to standardize pull request submissions.
    - Added a .pre-commit-config.yaml file to configure pre-commit hooks for code quality and formatting checks.
    - Introduced a .safety-policy.yml file for managing security policies and vulnerability scanning.
    - Added placeholder test files and directories for unit and integration tests.
- **CI**:
    - Set up GitHub Actions workflows for code quality, testing, PR validation, documentation checks, and vulnerability scans.
- **Documentation**:
    - Significantly updated the README.md to include badges, detailed sections, and a table of contents.
    - Added Sphinx configuration and Makefile for generating project documentation.
- **Tests**:
    - Added placeholder test files for unit and integration tests to avoid errors during test runs.
- **Chores**:
    - Added a .cruft.json file to manage project template updates.
    - Included a .readthedocs.yaml file for configuring Read the Docs builds.
    - Added a .yamllint.yaml file for YAML linting configuration.

### CODE REVIEW

**Comment by JaeAeich** [comment]
changing the base to be able to check CI, this is not supposed to be merged in main but maybe in basic-structure branch.

**Comment by JaeAeich** [comment]
@uniqueg @psankhe28 finally this fixes all the issues that we have been facing hopefully.

CI for code test are failing because this repo is does not have `CODECOV_TOKEN`, so that should pass those test as well.
Base branch is main because otherwise I couldnt test CI stuff, now easiest way would be either merge this into main or merge this branch into yours and merge that into main.

@uniqueg for anyone to now create a new repo with all the  test passing would be to create the repo and be sure to generate docs using `make d` and push it. This should pass all the CI, given all the TOKENs are in place.
I have extensively tested cookiecutter and made change accordingly, so I think we should be good to merge this [PR](https://github.com/elixir-cloud-aai/cookiecutter-python/pull/1) as well.

**Comment by uniqueg** [comment]
See https://github.com/elixir-cloud-aai/tus-storagehandler/pull/3#issuecomment-2250167889 and the comment above, @JaeAeich & @psankhe28

**Comment by JaeAeich** [comment]
refer to #10

**Pull request closed without merging**
